=== dirs26/HITO_IND2_LM/tienda.dtd
<!ELEMENT tienda_stockx (anho_2021,anho_2022)>
<!ELEMENT anho_2021 (trimestre1,trimestre2,trimestre3,trimestre4)>
<!ELEMENT anho_2022 (trimestre1,trimestre2,trimestre3,trimestre4)>
<!ELEMENT trimestre1 (usuarios+)>
<!ELEMENT trimestre2 (usuarios+)>
<!ELEMENT trimestre3 (usuarios+)>
<!ELEMENT trimestre4 (usuarios+)>
<!ELEMENT usuarios (numero, nombre, apellido, telefono, dir, correo, fecha_inclusión, pedidos)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (primerA, segundoA)>
<!ELEMENT primerA (#PCDATA)>
<!ELEMENT segundoA (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT dir (calle, ciu, prov, cp)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT ciu (#PCDATA)>
<!ELEMENT prov (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT fecha_inclusión (#PCDATA)>
<!ELEMENT pedidos (num_pedido, fecha_pedido, fecha_entrega, total, producto)>
<!ELEMENT num_pedido (#PCDATA)>
<!ELEMENT fecha_pedido (#PCDATA)>
<!ELEMENT fecha_entrega (#PCDATA)>
<!ELEMENT total (#PCDATA)>
<!ELEMENT producto (nombre_producto, referencia_producto, precio_producto, unidades_producto)>
<!ELEMENT nombre_producto (#PCDATA)>
<!ELEMENT referencia_producto (#PCDATA)>
<!ELEMENT precio_producto (#PCDATA)>
<!ELEMENT unidades_producto (#PCDATA)>

=== dirs26/HITO_IND2_LM/tienda.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE tienda_stockx SYSTEM "tienda.dtd">
<tienda_stockx>
  <anho_2021>
    <trimestre1>
      <usuarios>
        <numero>1</numero>
        <nombre>Sander</nombre>
        <apellido>
          <primerA>Darcey</primerA>
          <segundoA>Franzonetti</segundoA>
        </apellido>
        <telefono>806424347</telefono>
        <dir>
          <calle>Male</calle>
          <ciu>Lubbock</ciu>
          <prov>Texas</prov>
          <cp>79410</cp>
        </dir>
        <correo>sfranzonetti0@deviantart.com</correo>
        <fecha_inclusión>22/02/2021</fecha_inclusión>
        <pedidos>
          <num_pedido>51</num_pedido>
          <fecha_pedido>28/02/2021</fecha_pedido>
          <fecha_entrega>14/03/2021</fecha_entrega>
          <total>€300</total>
          <producto>
            <nombre_producto>Dunk Low Retro White Black Panda</nombre_producto>
            <referencia_producto>4567876543</referencia_producto>
            <precio_producto>€150</precio_producto>
            <unidades_producto>2</unidades_producto>
          </producto>
        </pedidos>
      </usuarios>
      <usuarios>
        <numero>2</numero>
        <nombre>Rowen</nombre>
        <apellido>
          <primerA>Greenstock</primerA>
          <segundoA>Dufall</segundoA>
        </apellido>
        <telefono>2125987631</telefono>
        <dir>
          <calle>Male</calle>
          <ciu>New York City</ciu>
          <prov>New York</prov>
          <cp>10292</cp>
        </dir>
        <correo>rdufall1@fotki.com</correo>
        <fecha_inclusión>27/01/2021</fecha_inclusión>
        <pedidos>
          <num_pedido>96</num_pedido>
          <fecha_pedido>30/01/2021</fecha_pedido>
          <fecha_entrega>17/02/2021</fecha_entrega>
          <total>€175</total>
          <producto>
            <nombre_producto>Nike Zoom Cortez SP sacai Iron Grey</nombre_producto>
            <referencia_producto>4536298354</referencia_producto>
            <precio_producto>€175</precio_producto>
            <unidades_producto>1</unidades_producto>
          </producto>
        </pedidos>
      </usuarios>
      <usuarios>
        <numero>3</numero>
        <nombre>Tamiko</nombre>
        <apellido>
          <primerA>Durrans</primerA>
          <segundoA>Haresign</segundoA>
        </apellido>
        <telefono>2604765529</telefono>
        <dir>
          <calle>Female</calle>
          <ciu>Fort Wayne</ciu>
          <prov>Indiana</prov>
          <cp>46814</cp>
        </dir>
        <correo>tharesign2@clickbank.net</correo>
        <fecha_inclusión>25/01/2021</fecha_inclusión>
        <pedidos>
          <num_pedido>14</num_pedido>
          <fecha_pedido>09/03/2021</fecha_pedido>
          <fecha_entrega>20/03/2021</fecha_entrega>
          <total>€210</total>
          <producto>
            <nombre_producto>Kaws x Uniqlo Clean Slate Tee</nombre_producto>
            <referencia_producto>2341526378</referencia_producto>
            <precio_producto>€70</precio_producto>
            <unidades_producto>3</unidades_producto>
          </producto>
        </pedidos>
      </usuarios>
      <usuarios>
        <numero>4</numero>
        <nombre>Byrann</nombre>
        <apellido>
          <primerA>Parkeson</primerA>
          <segundoA>Burchill</segundoA>
        </apellido>
        <telefono>7186098434</telefono>
        <dir>
          <calle>Genderqueer</calle>
          <ciu>Bronx</ciu>
          <prov>New York</prov>
          <cp>10454</cp>
        </dir>
        <correo>bburchill3@addthis.com</correo>
        <fecha_inclusión>13/01/2021</fecha_inclusión>
        <pedidos>
          <num_pedido>76</num_pedido>
          <fecha_pedido>03/02/2021</fecha_pedido>
          <fecha_entrega>27/03/2021</fecha_entrega>
          <total>€120</total>
          <producto>
            <nombre_producto>Nike Blazer Low Off-White Black Electro Green</nombre_producto>
            <referencia_producto>7583904735</referencia_producto>
            <precio_producto>€120</precio_producto>
            <unidades_producto>1</unidades_producto>
          </producto>
        </pedidos>
      </usuarios>
      <usuarios>
        <numero>5</numero>
        <nombre>Bonny</nombre>
        <apellido>
          <primerA>Antonin</primerA>
          <segundoA>Sloy</segundoA>
        </apellido>
        <telefono>3034309612</telefono>
        <dir>
          <calle>Female</calle>
          <ciu>Denver</ciu>
          <prov>Colorado</prov>
          <cp>80241</cp>
        </dir>
        <correo>bsloy4@soundcloud.com</correo>
        <fecha_inclusión>07/01/2021</fecha_inclusión>
        <pedidos>
          <num_pedido>80</num_pedido>
          <fecha_pedido>21/01/2021</fecha_pedido>
          <fecha_entrega>04/02/2021</fecha_entrega>
          <total>€26.512</total>
          <producto>
            <nombre_producto>Nike Air Yeezy 2</nombre_producto>
            <referencia_producto>7453647492</referencia_producto>
            <precio_producto>€26.512</precio_producto>
            <unidades_producto>1</unidades_producto>
          </producto>
        </pedidos>
      </usuarios>
      <usuarios>
        <numero>6</numero>
        <nombre>Wells</nombre>
        <apellido>
          <primerA>Lovitt</primerA>
          <segundoA>Langfitt</segundoA>
        </apellido>
        <telefono>9732047192</telefono>
        <dir>
          <calle>Male</calle>
          <ciu>Newark</ciu>
          <prov>New Jersey</prov>
          <cp>07104</cp>
        </dir>
        <correo>wlangfitt5@answers.com</correo>
        <fecha_inclusión>20/05/2022</fecha_inclusión>
        <pedidos>
          <num_pedido>91</num_pedido>
          <fecha_pedido>09/03/2021</fecha_pedido>
          <fecha_entrega>29/03/2021</fecha_entrega>
          <total>€1.200</total>
          <producto>
            <nombre_producto>Jordan 4 Retro SE Craft Photon Dust</nombre_producto>
            <referencia_producto>9407342637</referencia_producto>
            <precio_producto>€300</precio_producto>
            <unidades_producto>4</unidades_producto>
          </producto>
        </pedidos>
      </usuarios>
      <usuarios>
        <numero>7</numero>
        <nombre>Aleen</nombre>
        <apellido>
          <primerA>Caton</primerA>
          <segundoA>Corley</segundoA>
        </apellido>
        <telefono>7606102373</telefono>
        <dir>
          <calle>Agender</calle>
          <ciu>Escondido</ciu>
          <prov>California</prov>
          <cp>92030</cp>
        </dir>
        <correo>acorley6@digg.com</correo>
        <fecha_inclusión>04/01/2021</fecha_inclusión>
        <pedidos>
          <num_pedido>88</num_pedido>
          <fecha_pedido>25/01/2021</fecha_pedido>
          <fecha_entrega>01/02/2021</fecha_entrega>
          <total>€348</total>
          <producto>
            <nombre_producto>Puma LaMelo Ball MB.02 Rick and Morty Adventures</nombre_producto>
            <referencia_producto>7453627389</referencia_producto>
            <precio_producto>€174</precio_producto>
            <unidades_producto>2</unidades_producto>
          </producto>
        </pedidos>
      </usuarios>
      <usuarios>
        <numero>8</numero>
        <nombre>Jimmie</nombre>
        <apellido>
          <primerA>Straughan</primerA>
          <segundoA>Bushe</segundoA>
        </apellido>
        <telefono>3182564296</telefono>
        <dir>
          <calle>Male</calle>
          <ciu>Shreveport</ciu>
          <prov>Louisiana</prov>
          <cp>71130</cp>
        </dir>
        <correo>jbushe7@is.gd</correo>
        <fecha_inclusión>25/01/2021</fecha_inclusión>
        <pedidos>
          <num_pedido>92</num_pedido>
          <fecha_pedido>06/02/2021</fecha_pedido>
          <fecha_entrega>15/02/2021</fecha_entrega>
          <total>€209</total>
          <producto>
            <nombre_producto>Nike x Stussy Knit Sweater Natural</nombre_producto>
            <referencia_producto>6472893630</referencia_producto>
            <precio_producto>€209</precio_producto>
            <unidades_producto>1</unidades_producto>
          </producto>
        </pedidos>
      </usuarios>
      <usuarios>
        <numero>9</numero>
        <nombre>Minda</nombre>
        <apellido>
          <primerA>Fittes</primerA>
          <segundoA>Manoelli</segundoA>
        </apellido>
        <telefono>5704573873</telefono>
        <dir>
          <calle>Female</calle>
          <ciu>Wilkes Barre</ciu>
          <prov>Pennsylvania</prov>
          <cp>18763</cp>
        </dir>
        <correo>mmanoelli8@gnu.org</correo>
        <fecha_inclusión>21/01/2022</fecha_inclusión>
        <pedidos>
          <num_pedido>18</num_pedido>
          <fecha_pedido>02/02/2022</fecha_pedido>
          <fecha_entrega>22/03/2022</fecha_entrega>
          <total>€1.748</total>
          <producto>
            <nombre_producto>Goyard Saint Sulpice Black Natural</nombre_producto>
            <referencia_producto>6453835263</referencia_producto>
            <precio_producto>€437</precio_producto>
            <unidades_producto>4</unidades_producto>
          </producto>
        </pedidos>
      </usuarios>
      <usuarios>
        <numero>10</numero>
        <nombre>Weylin</nombre>
        <apellido>
          <primerA>Dockrey</primerA>
          <segundoA>Hughesdon</segundoA>
        </apellido>
        <telefono>5028947365</telefono>
        <dir>
          <calle>Male</calle>
          <ciu>Louisville</ciu>
          <prov>Kentucky</prov>
          <cp>40293</cp>
        </dir>
        <correo>whughesdon9@nature.com</correo>
        <fecha_inclusión>23/02/2021</fecha_inclusión>
        <pedidos>
          <num_pedido>48</num_pedido>
